### ISSUE TITLE
Uncaught TypeError: (null)(): supplied resource is not a valid stream resource in [no active file]:0

### ISSUE THREAD

**Issue by ennorehling** [overtrue/phplint#212] opened 2024-09-07 10:44 UTC
# New Issue

## Diagnose

> If you use a Composer installation, please specify:

<details>
<summary>Output of `composer show` command</summary>

```
amphp/amp                              3.0.2    A non-blocking concurrency framework for PHP applications.
amphp/byte-stream                      2.1.1    A stream abstraction to make working with non-blocking I/O simple.
amphp/cache                            2.0.1    A fiber-aware cache API based on Amp and Revolt.
amphp/dns                              2.2.0    Async DNS resolution for Amp.
amphp/parallel                         2.2.9    Parallel processing component for Amp.
amphp/parser                           1.1.1    A generator parser to make streaming parsers simple.
amphp/pipeline                         1.2.1    Asynchronous iterators and operators.
amphp/process                          2.0.3    A fiber-aware process manager based on Amp and Revolt.
amphp/serialization                    1.0.0    Serialization tools for IPC and data storage in PHP.
amphp/socket                           2.3.1    Non-blocking socket connection / server implementations based on Amp and Revolt.
amphp/sync                             2.3.0    Non-blocking synchronization primitives for PHP based on Amp and Revolt.
amphp/windows-registry                 1.0.1    Windows Registry Reader.
brick/math                             0.12.1   Arbitrary-precision arithmetic library
carbonphp/carbon-doctrine-types        2.1.0    Types to use Carbon in Doctrine
composer/pcre                          3.3.1    PCRE wrapping library that offers type-safe preg_* replacements.
composer/semver                        3.4.2    Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler                3.0.5    Restarts a process without Xdebug.
daverandom/libdns                      2.1.0    DNS protocol implementation written in pure PHP
dflydev/dot-access-data                3.0.3    Given a deep data structure, access data by dot notation.
doctrine/cache                         2.2.0    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/dbal                          3.9.1    Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                  1.1.3    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/event-manager                 2.0.1    The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                     2.0.10   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/lexer                         3.0.1    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression          3.3.3    CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator                4.0.2    A library for validating emails against several RFCs
fakerphp/faker                         1.23.1   Faker is a PHP library that generates fake data for you.
felixfbecker/advanced-json-rpc         3.2.1    A more advanced JSONRPC implementation
filp/whoops                            2.15.4   php error handling for cool kids
firebase/php-jwt                       6.10.1   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
fruitcake/php-cors                     1.3.0    Cross-origin resource sharing library for the Symfony HttpFoundation
graham-campbell/result-type            1.1.3    An Implementation Of The Result Type
guzzlehttp/guzzle                      7.9.2    Guzzle is a PHP HTTP client library
guzzlehttp/promises                    2.0.3    Guzzle promises library
guzzlehttp/psr7                        2.7.0    PSR-7 message implementation that also provides common utility methods
guzzlehttp/uri-template                1.0.3    A polyfill class for uri_template of PHP
hamcrest/hamcrest-php                  2.0.1    This is the PHP port of Hamcrest Matchers
kelunik/certificate                    1.1.3    Access certificate details and transform between different formats.
laravel/framework                      10.48.20 The Laravel Framework.
laravel/pint                           1.17.3   An opinionated code formatter for PHP.
laravel/prompts                        0.1.25   Add beautiful and user-friendly forms to your command-line applications.
laravel/sail                           1.31.3   Docker files for running a basic Laravel application.
laravel/sanctum                        3.3.3    Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.
laravel/serializable-closure           1.3.4    Laravel Serializable Closure provides an easy and secure way to serialize closures in PHP.
laravel/tinker                         2.9.0    Powerful REPL for the Laravel framework.
league/commonmark                      2.5.3    Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and GitHub-Flavored Markdown (GFM)
league/config                          1.2.0    Define configuration arrays with strict schemas and access values with dot notation
league/flysystem                       3.28.0   File storage abstraction for PHP
league/flysystem-local                 3.28.0   Local filesystem adapter for Flysystem.
league/mime-type-detection             1.15.0   Mime-type detection for Flysystem
league/uri                             7.4.1    URI manipulation library
league/uri-interfaces                  7.4.1    Common interfaces and classes for URI representation and interaction
microsoft/tolerant-php-parser          0.1.2    Tolerant PHP-to-AST parser designed for IDE usage scenarios
mockery/mockery                        1.6.12   Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                        3.7.0    Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                      1.12.0   Create deep copies (clones) of your objects
nesbot/carbon                          2.72.5   An API extension for DateTime that supports 281 different languages.
netresearch/jsonmapper                 4.4.1    Map nested JSON structures onto PHP classes
nette/schema                           1.3.0    📐 Nette Schema: validating data structures against a given Schema.
nette/utils                            4.0.5    🛠  Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or strong password generating etc.
nikic/php-parser                       5.1.0    A PHP parser written in PHP
nunomaduro/collision                   7.10.0   Cli error handling for console/command-line PHP applications.
nunomaduro/termwind                    1.15.1   Its like Tailwind CSS, but for the console.
overtrue/phplint                       9.4.1    `phplint` is a tool that can speed up linting of php files by running several lint processes at once.
phan/phan                              5.4.5    A static analyzer for PHP
phar-io/manifest                       2.0.4    Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                        3.2.1    Library for handling version information and constraints
phpdocumentor/reflection-common        2.2.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock      5.4.1    With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver            1.8.2    A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                    1.9.3    Option Type for PHP
phpstan/phpdoc-parser                  1.30.0   PHPDoc parser with support for nullable, intersection and generic types
phpunit/php-code-coverage              10.1.16  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator              4.1.0    FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                    4.0.0    Invoke callables with a timeout
phpunit/php-text-template              3.0.1    Simple template engine.
phpunit/php-timer                      6.0.0    Utility class for timing
phpunit/phpunit                        10.5.32  The PHP Unit Testing framework.
psr/cache                              3.0.0    Common interface for caching libraries
psr/clock                              1.0.0    Common interface for reading the clock.
psr/container                          2.0.2    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                   1.0.0    Standard interfaces for event handling.
psr/http-client                        1.0.3    Common interface for HTTP clients
psr/http-factory                       1.1.0    PSR-17: Common interfaces for PSR-7 HTTP message factories
psr/http-message                       2.0      Common interface for HTTP messages
psr/log                                3.0.1    Common interface for logging libraries
psr/simple-cache                       3.0.0    Common interfaces for simple caching
psy/psysh                              0.12.4   An interactive shell for modern PHP.
ralouphie/getallheaders                3.0.3    A polyfill for getallheaders.
ramsey/collection                      2.0.0    A PHP library for representing and manipulating collections.
ramsey/uuid                            4.7.6    A PHP library for generating and working with universally unique identifiers (UUIDs).
revolt/event-loop                      1.0.6    Rock-solid event loop for concurrent PHP applications.
sabre/event                            5.1.7    sabre/event is a library for lightweight event-based programming
sebastian/cli-parser                   2.0.1    Library for parsing CLI options
sebastian/code-unit                    2.0.0    Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup     3.0.0    Looks up which function or method a line of code belongs to
sebastian/comparator                   5.0.2    Provides the functionality to compare PHP values for equality
sebastian/complexity                   3.2.0    Library for calculating the complexity of PHP code units
sebastian/diff                         5.1.1    Diff implementation
sebastian/environment                  6.1.0    Provides functionality to handle HHVM/PHP environments
sebastian/exporter                     5.1.2    Provides the functionality to export PHP variables for visualization
sebastian/global-state                 6.0.2    Snapshotting of global state
sebastian/lines-of-code                2.0.2    Library for counting the lines of code in PHP source code
sebastian/object-enumerator            5.0.0    Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector             3.0.0    Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context            5.0.0    Provides functionality to recursively process PHP variables
sebastian/type                         4.0.0    Collection of value objects that represent the types of the PHP type system
sebastian/version                      4.0.1    Library that helps with managing the version number of Git-hosted PHP projects
spatie/backtrace                       1.6.2    A better backtrace
spatie/error-solutions                 1.1.1    This is my package error-solutions
spatie/flare-client-php                1.8.0    Send PHP errors to Flare
spatie/ignition                        1.15.0   A beautiful error page for PHP applications.
spatie/laravel-data                    3.12.0   Create unified resources and data transfer objects
spatie/laravel-http-logger             1.11.0   A Laravel package to log HTTP requests
spatie/laravel-ignition                2.8.0    A beautiful error page for Laravel applications.
spatie/laravel-package-tools           1.16.5   Tools for creating Laravel packages
spatie/php-structure-discoverer        2.2.0    Automatically discover structures within your PHP application
squizlabs/php_codesniffer              3.10.2   PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
symfony/cache                          6.4.11   Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts                3.5.0    Generic abstractions related to caching
symfony/console                        6.4.11   Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                   6.4.8    Converts CSS selectors to XPath expressions
symfony/deprecation-contracts          3.5.0    A generic function and convention to trigger deprecation notices
symfony/error-handler                  6.4.10   Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher               6.4.8    Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts     3.5.0    Generic abstractions related to dispatching event
symfony/finder                         6.4.11   Finds files and directories via an intuitive fluent interface
symfony/http-foundation                6.4.10   Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                    6.4.11   Provides a structured process for converting a Request into a Response
symfony/mailer                         6.4.9    Helps sending emails
symfony/mime                           6.4.11   Allows manipulating MIME messages
symfony/options-resolver               6.4.8    Provides an improved replacement for the array_replace PHP function
symfony/polyfill-ctype                 1.30.0   Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme         1.30.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn              1.30.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer       1.30.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring              1.30.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                 1.30.0   Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php80                 1.30.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php83                 1.30.0   Symfony polyfill backporting some PHP 8.3+ features to lower PHP versions
symfony/polyfill-uuid                  1.30.0   Symfony polyfill for uuid functions
symfony/process                        6.4.8    Executes commands in sub-processes
symfony/routing                        6.4.11   Maps an HTTP request to a set of configuration variables
symfony/service-contracts              3.5.0    Generic abstractions related to writing services
symfony/string                         6.4.11   Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                    6.4.10   Provides tools to internationalize your application
symfony/translation-contracts          3.5.0    Generic abstractions related to translation
symfony/uid                            6.4.11   Provides an object-oriented API to generate and represent UIDs
symfony/var-dumper                     6.4.11   Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                   6.4.9    Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                           6.4.11   Loads and dumps YAML files
theseer/tokenizer                      1.2.3    A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles      2.2.7    CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
tysonandre/var_representation_polyfill 0.1.3    Polyfill for var_representation: convert a variable to a string in a way that fixes the shortcomings of var_export
vlucas/phpdotenv                       5.6.1    Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                    2.0.1    Portable ASCII library - performance optimized (ascii) string functions for php.
webmozart/assert                       1.11.0   Assertions to validate method input/output with nice error messages.
```

</details>

> If you use Docker image of PHP Lint, please specify:

<details>
<summary>Output of `docker inspect overtrue/phplint:latest` command</summary>

```
...REPLACE ME...
```

</details>

> If you use PHAR version of PHP Lint, please specify:

<details>
<summary>Output of `phplint.phar --manifest` command</summary>

```
...REPLACE ME...
```

</details>

## Summary

After upgrading from phplint 9.1.2 to 9.4.1, I see this message:
```
PHP Fatal error:  Uncaught TypeError: (null)(): supplied resource is not a valid stream resource in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0
```

## Expected behaviour

I imagine to see only the lint results.

## Actual behaviour

I see the lint results, and that "Uncaught TypeError" error message.

**Comment by ennorehling** [comment] 2024-09-07 13:43
PHP 8.1.28
My command is `vendor/bin/phplint .`

The analyzed source code doesn't matter. It happens even with this single file:
```
<?php
phpinfo();
```

![image](https://github.com/user-attachments/assets/61b04684-77db-4f6f-b8e4-289abdc18c97)

**Comment by llaville** [comment] 2024-09-07 13:47
Could you give us the contents of your `.phplint.yml` config file please ?

**Comment by ennorehling** [comment] 2024-09-07 13:50
Sure, this is my standard phplint.yml:
```
jobs: 10
extensions:
  - php
exclude:
  - vendor
warning: true
memory-limit: -1
cache: /tmp/.phplint.cache
no-cache: false
log-json: false
log-junit: false
```

**Comment by llaville** [comment] 2024-09-07 14:12
Even if I've a more recent version of PHP 8.1 

In screenshot `custom.php` is your phpinfo file, and `custom.phplint.yml` your config file 

![issue](https://github.com/user-attachments/assets/8b6cc906-90eb-4fb1-b4c8-d710810f1efd)

As I cannot reproduced your error, I suspect that it came from your PHP platform itself after doing a quick google search.
See https://www.workerman.net/q/6519

Could you restart your PHP server and see if it solve the situation ?

**Comment by llaville** [comment] 2024-09-08 04:42
Without reply, I supposed you've found origin of your issue ?
Feel free to close this report, and perharps give an answer to help community if they have the same problem.

**Comment by ennorehling** [comment] 2024-09-08 15:14
It is the weekend, I'm not at work today, and have not found a solution.

Even with the same command line that you use, I still get the error.
![image](https://github.com/user-attachments/assets/5e5743d7-690b-4ce2-bb75-c414a528b093)

The page you linked seems to blame swoole, which I've never heard of and I'm not using.

I don't know what you mean by "restart my PHP server" - I'm running PHP from the command line on Ubuntu 22.04.

**Comment by ennorehling** [comment] 2024-09-08 15:18
Actually, it turns out I **do** have swoole installed as part of Laravel Sail. I'll have to figure out how to remove it and will report back.

**Comment by llaville** [comment] 2024-09-12 03:43
Any news ?

**Comment by ennorehling** [comment] 2024-09-12 19:04
Nothing yet. Not the highest priority problem I'm dealing with at the moment.

**Comment by llaville** [comment] 2024-09-16 07:11
As your `composer show` command results identified lot of other dependencies than those expected by PHPLint itself, you've probably tried to used it inside your project as any other dependency.

As it seems, you've not found yet your problem, I suggest you to test only PHPLint (with PHAR distribution, for example) to see if you got again the same issue. But I'm pretty sure you won't have !

If you can gave an answer that proove PHPLint if faulty, then feel free to re-open this report.

**Closed by llaville** 2024-09-16 07:11 UTC
