### ISSUE TITLE
Problem with symbolic links

### ISSUE THREAD

**Issue by StrathCole** [overtrue/phplint#71] opened 2020-04-16 08:55 UTC
I am using phplint from gitlab with repositories that contain symbolic links where targets are not inside the repository.
phplint seems not to be able to handle this and dies with exception. Version is 1.2.1.

Config is:
```
path: ./
jobs: 10
cache: .phplint-cache
extensions:
  - php
exclude:
  - vendor
```

```
 There was 1 errors:
1. 0:0
PHP Warning:  file(0): failed to open stream: No such file or directory in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 314
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:207
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:298
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:347
PHP  10. file() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:314
PHP Warning:  array_slice() expects parameter 1 to be array, boolean given in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 318
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:207
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:298
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:347
PHP  10. array_slice() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:318
PHP Warning:  end() expects parameter 1 to be array, null given in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 319
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:207
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:298
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:347
PHP  10. end() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:319
PHP Warning:  key() expects parameter 1 to be array, null given in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 320
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:207
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:298
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:347
PHP  10. key() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:320
PHP Warning:  Invalid argument supplied for foreach() in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 323
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:207
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:298
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:347
 Could not open input file:
```

**Comment by overtrue** [comment] 2020-04-16 15:49
plz upgrade to 1.2.2 and test again, I can't reproduce the problem.

**Comment by StrathCole** [comment] 2020-04-16 18:18
Done. But sadly it persists:
```
There was 1 errors:
1. 0:0
PHP Warning:  file(0): failed to open stream: No such file or directory in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 353
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:218
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:337
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:386
PHP  10. file() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:353
PHP Warning:  array_slice() expects parameter 1 to be array, boolean given in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 357
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:218
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:337
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:386
PHP  10. array_slice() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:357
PHP Warning:  end() expects parameter 1 to be array, null given in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 358
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:218
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:337
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:386
PHP  10. end() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:358
PHP Warning:  key() expects parameter 1 to be array, null given in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 359
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:218
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:337
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:386
PHP  10. key() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:359
PHP Warning:  Invalid argument supplied for foreach() in /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php on line 362
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Command\LintCommand->showErrors() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:218
PHP   8. Overtrue\PHPLint\Command\LintCommand->getHighlightedCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:337
PHP   9. Overtrue\PHPLint\Command\LintCommand->getCodeSnippet() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:386
 Could not open input file:
```

**Comment by StrathCole** [comment] 2020-04-16 18:25
Problem seems to be this:
https://github.com/overtrue/phplint/blob/master/src/Command/LintCommand.php#L337

When an error in Command->run occurs (because file is a symlink that is not existing) then it triggers the error without checking if the file exists before opening it with `file()`.

**Comment by StrathCole** [comment] 2020-04-16 18:29
You should be able to reproduce this like this:

`cd /myproject`  
`mkdir includes`  
`ln -s /path/not/existing includes/mylib.inc.php`

And then run phplint with this config:
```
path: ./
jobs: 10
cache: .phplint-cache
extensions:
  - php
exclude:
  - vendor
```

**Comment by overtrue** [comment] 2020-04-16 23:12
Sorry, I misunderstood your scene. It's fixed now.

**Closed** 2020-04-16 23:11 UTC

**Comment by overtrue** [comment] 2020-04-16 23:13
https://github.com/overtrue/phplint/commit/f71100ae49d833863ef5eb819e58e362ac9a6b96#diff-d65ec871dabaddc72b967fe5a369fcbdR186-R188

**Comment by StrathCole** [comment] 2020-04-17 06:05
Thank you, it seems that the commit introduced a new problem.

```
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php on line 88
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Linter->getFiles() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:192
PHP   8. Overtrue\PHPLint\Linter->getFilesFromDir() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:163
PHP   9. iterator_to_array() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  10. Symfony\Component\Finder\Finder->getIterator() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  11. Symfony\Component\Finder\Finder->searchInDirectory() /builds/my-project/vendor/symfony/finder/Finder.php:571
PHP  12. Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator->__construct() /builds/my-project/vendor/symfony/finder/Finder.php:686
PHP  13. Symfony\Component\Finder\Iterator\FilenameFilterIterator->toRegex() /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php:34
PHP  14. Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator->isRegex() /builds/my-project/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:45
PHP  15. preg_match() /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php:88
PHP Warning:  strlen() expects parameter 1 to be string, array given in /builds/my-project/vendor/symfony/finder/Glob.php on line 54
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Linter->getFiles() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:192
PHP   8. Overtrue\PHPLint\Linter->getFilesFromDir() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:163
PHP   9. iterator_to_array() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  10. Symfony\Component\Finder\Finder->getIterator() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  11. Symfony\Component\Finder\Finder->searchInDirectory() /builds/my-project/vendor/symfony/finder/Finder.php:571
PHP  12. Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator->__construct() /builds/my-project/vendor/symfony/finder/Finder.php:686
PHP  13. Symfony\Component\Finder\Iterator\FilenameFilterIterator->toRegex() /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php:34
PHP  14. Symfony\Component\Finder\Glob::toRegex() /builds/my-project/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:45
PHP  15. strlen() /builds/my-project/vendor/symfony/finder/Glob.php:54
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php on line 88
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Linter->getFiles() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:192
PHP   8. Overtrue\PHPLint\Linter->getFilesFromDir() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:163
PHP   9. iterator_to_array() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  10. Symfony\Component\Finder\Finder->getIterator() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  11. Symfony\Component\Finder\Finder->searchInDirectory() /builds/my-project/vendor/symfony/finder/Finder.php:571
PHP  12. Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator->__construct() /builds/my-project/vendor/symfony/finder/Finder.php:706
PHP  13. Symfony\Component\Finder\Iterator\PathFilterIterator->toRegex() /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php:38
PHP  14. Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator->isRegex() /builds/my-project/vendor/symfony/finder/Iterator/PathFilterIterator.php:54
PHP  15. preg_match() /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php:88
PHP Warning:  preg_quote() expects parameter 1 to be string, array given in /builds/my-project/vendor/symfony/finder/Iterator/PathFilterIterator.php on line 54
PHP Stack trace:
PHP   1. {main}() /builds/my-project/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Symfony\Component\Console\Application->run() /builds/my-project/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Symfony\Component\Console\Application->doRun() /builds/my-project/vendor/symfony/console/Application.php:130
PHP   4. Symfony\Component\Console\Application->doRunCommand() /builds/my-project/vendor/symfony/console/Application.php:228
PHP   5. Symfony\Component\Console\Command\Command->run() /builds/my-project/vendor/symfony/console/Application.php:874
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /builds/my-project/vendor/symfony/console/Command/Command.php:264
PHP   7. Overtrue\PHPLint\Linter->getFiles() /builds/my-project/vendor/overtrue/phplint/src/Command/LintCommand.php:192
PHP   8. Overtrue\PHPLint\Linter->getFilesFromDir() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:163
PHP   9. iterator_to_array() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  10. Symfony\Component\Finder\Finder->getIterator() /builds/my-project/vendor/overtrue/phplint/src/Linter.php:193
PHP  11. Symfony\Component\Finder\Finder->searchInDirectory() /builds/my-project/vendor/symfony/finder/Finder.php:571
PHP  12. Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator->__construct() /builds/my-project/vendor/symfony/finder/Finder.php:706
PHP  13. Symfony\Component\Finder\Iterator\PathFilterIterator->toRegex() /builds/my-project/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php:38
PHP  14. preg_quote() /builds/my-project/vendor/symfony/finder/Iterator/PathFilterIterator.php:54
Could not find files to lint
```

**Comment by overtrue** [comment] 2020-04-17 06:20
I am sorry, I found it: 

3.x - 4.1 https://github.com/symfony/finder/blob/4.1/Finder.php#L168
4.2 + https://github.com/symfony/finder/blob/4.2/Finder.php#L173
